### PR TITLE
minimega: remove meshage timeout.

### LINKED ISSUE #504: minimega/mesh: `vm start` timeout
When you call `vm start all`, it blocks until all the VMs that were launched with `vm launch ... noblock` have been created and started. This may cause timeouts with `mesh send`.

I propose that we get rid of this timeout -- we should trust that the node responds or crashes. If the node crashes, we should see an error from the connection's reader.

Perhaps we could support interrupting "long-running" commands with `Ctrl-C` if commands truly get stuck (e.g. `mesh send` and `read`).

### PR DESCRIPTION
**Pull request by jcrussell**
Fixes #504. Set the default timeout to 0 which implies no timeout. Users
can set a timeout using `mesh timeout`, if needed.

### CODE REVIEW

File: src/minimega/meshage.go [hunk 1]
```diff
@@ -168,8 +163,15 @@ func meshageSend(c *minicli.Command, hosts string) (chan minicli.Responses, erro
 
 		log.Debug("meshage sent, waiting on %d responses", len(recipients))
 
+		// host -> response
 		resps := map[string]*minicli.Response{}
 
+		timeout := meshageTimeout
+		// If the timeout is 0, set to "unlimited"
+		if timeout == 0 {
+			timeout = math.MaxInt64
```
Comment (djfritz) [inline src/minimega/meshage.go]: But what if I issue a command that naturally takes longer than the expected remaining lifetime of the sun?

**Comment by djfritz** [comment]
LGTM

File: src/minimega/meshage.go (hunk 1 above)
Comment (jcrussell) [inline src/minimega/meshage.go]: Hah. Fortunately, time.Duration is a nanosecond count so that's only ~290 years.
